import { baseUrl } from "../../config";
export const ALL_REDUCER_OBJECTS = {
  PHYSICIAN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Group/getAll",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "PHYSICIAN_GROUP",
    name: "physician",
  },
  LOOKUP_USERTYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=usertype",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_USERTYPE_API",
    name: "lookUpUserType",
  },

  LOOKUP_STATE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=State",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_STATE_API",
    name: "lookUpState",
  },
  PHONE_TYPE_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=phoneType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "PHONE_TYPE_LOOKUP",
    name: "phoneTypeLookup",
  },

  CONTACT_TYPE_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=contactType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CONTACT_TYPE_LOOKUP",
    name: "contactTypeLookup",
  },
  IDENTIFICATION_TYPE_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=identificationType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "IDENTIFICATION_TYPE_LOOKUP",
    name: "identificationTypeLookup",
  },

  LOOKUP_STATUS_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=status",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_STATUS_API",
    name: "lookUpStatus",
  },
  LOOKUP_DR_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=doctorType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_DR_TYPE",
    name: "lookUpDrType",
  },
  ADD_PHYSICIAN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Group/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_PHYSICIAN_GROUP",
    name: "addPhysicianGroup",
  },
  LOOKUP_FIELD_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=fieldType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_FIELD_TYPE_API",
    name: "lookUpFieldType",
  },
  // #######
  MODIFIERS_DROPDOWN_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Modifiers/modifierDropdown",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "MODIFIERS_DROPDOWN",
    name: "modifiersDropdown",
  },
  ADD_PHYSICIAN_GROUP_LOCATION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Group/createOrUpdateLocation",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_PHYSICIAN_GROUP_LOCATION",
    name: "addPhysicianGroupLocation",
  },
  EDIT_PHYSICIAN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Group/groupUpdate",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_PHYSICIAN_GROUP",
    name: "editPhysicianGroup",
  },
  VIEW_PHYSICIAN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Group/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "VIEW_PHYSICIAN_GROUP",
    name: "viewPhysicianGroup",
  },
  GET_PHYSICIANS_BY_GROUP_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Physician/getPhysiciansByGroupId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_PHYSICIANS_BY_GROUP_ID",
    name: "getPhysiciansByGroupId",
  },
  GET_UN_ASSIGNED_PHYSICIANS_BY_CLINIC_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Physician/getUnAssignedClinicPhysicians",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_UN_ASSIGNED_PHYSICIANS_BY_CLINIC_ID",
    name: "getUnAssignedPhysiciansByClinicId",
  },
  ADD_PHYSICIANS_IN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Physician/updatePhysicianGroup",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_PHYSICIANS_IN_GROUP",
    name: "addPhysiciansInGroup",
  },
  ASSIGN_PHYSICIAN_BY_GROUP_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Physician/assignPhysicianByGroupId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ASSIGN_PHYSICIAN_BY_GROUP_ID",
    name: "assignPhysicianByGroupId",
  },
  DELETE_PHYSICIANS_FROM_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Physician/deletePhysicianGroup",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_PHYSICIANS_FROM_GROUP",
    name: "deletePhysicianFromGroup",
  },
  DELETE_ALL_PHYSICIANS_FROM_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Physician/removeAllPhysicianGroupByGroupId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_ALL_PHYSICIANS_FROM_GROUP",
    name: "deleteAllPhysicianFromGroup",
  },
  GET_ALL_PHYSICIANS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Physician/getAllPhysicianList",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_PHYSICIANS",
    name: "getAllPhysicians",
  },
  VIEW_PHYSICIANS_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Physician/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "VIEW_PHYSICIANS",
    name: "viewPhysician",
  },
  ADD_PHYSICIAN_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Physician/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_PHYSICIAN_LOCATION",
    name: "addPhysician",
  },
  EDIT_PHYSICIAN_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Physician/physicianUpdate",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_PHYSICIAN",
    name: "editPhysician",
  },
  ADD_PHYSICIAN_LOCATION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Physician/createOrUpdateLocation",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_PHYSICIAN_LOCATION",
    name: "addPhysicianLocation",
  },
  UPDATE_PHYSICIAN_SETTING_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Physician/physicianSettingUpdate",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PHYSICIAN_SETTING",
    name: "updatePhysicianSetting",
  },
  UPDATE_PHYSICIAN_STATUS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Physician/updateStatus",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: " UPDATE_PHYSICIAN_STATUS",
    name: "updatePhysicianStatus",
  },
  GET_ALL_DEFAULT_TERM_BY_SECTION_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Goal/getAllTerm",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: " GET_ALL_DEFAULT_TERM_BY_SECTION_ID",
    name: "getAllDefaultTermBySectionId",
  },
  ADD_NEW_DEFAULT_TERM_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/createDefaultTerm",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_NEW_DEFAULT_TERM",
    name: "addNewDefaulTerm",
  },
  UPDATE_SINGLE_DEFAULT_TERM_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Goal/updateTerm",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_SINGLE_DEFAULT_TERM_OPTION",
    name: "updateSingleDefaultTermOption",
  },
  DELETE_SINGLE_DEFAULT_TERM_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteTerm",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_SINGLE_DEFAULT_TERM_OPTION",
    name: "deleteSingleDefaultTermOption",
  },
  GET_ALL_DEFAULT_DURATION_BY_SECTION_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Goal/getAllDurationm",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_DEFAULT_DURATION_BY_SECTION_ID",
    name: "getAllDefaultDurationBySectionId",
  },
  ADD_NEW_DEFAULT_DURATION_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/createDefaultDuration",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_NEW_DEFAULT_DURATION",
    name: "addNewDefaulDuration",
  },
  UPDATE_SINGLE_DEFAULT_DURATION_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Goal/updateDuration",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_SINGLE_DEFAULT_DURATION_OPTION",
    name: "updateSingleDefaultDurationOption",
  },
  DELETE_SINGLE_DEFAULT_DURATION_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteDuration",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_SINGLE_DEFAULT_DURATION_OPTION",
    name: "deleteSingleDefaultDurationOption",
  },
  GET_ALL_GOAL_GROUPS_BY_CLINIC_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Goal/getAllGoalGroupByClincId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_GOAL_GROUPS_BY_CLINIC_ID",
    name: "getAllGoalGroupsByClinicId",
  },
  ADD_GOAL_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/createGoalGroup",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_GOAL_GROUP",
    name: "addGoalGroup",
  },
  DELETE_SINGLE_GOAL_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteGoalGroup",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_SINGLE_GOAL_GROUP_API",
    name: "deleteSingleGoalGroup",
  },
  ADD_GOAL_GROUP_SECTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/createGoalSection",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_GOAL_GROUP_SECTION",
    name: "addGoalGroupSection",
  },
  GET_ALL_GOAL_SECTIONS_BY_GROUP_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Goal/getAllGoalSectionByGoalId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_GOAL_SECTIONS_BY_GROUP_ID",
    name: "getAllGoalSectionsByGroupId",
  },
  GET_ALL_GOALS_BY_SECTION_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Goal/getAllGoalSectionBySectionId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_GOALS_BY_SECTION_ID",
    name: "getAllGoalByBySectionId",
  },
  DELETE_SINGLE_GOAL_GROUP_SECTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteGoalSection",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_SINGLE_GOAL_GROUP_SECTION",
    name: "deleteSingleGoalGroupSection",
  },
  DELETE_DYNAMIC_HEADER_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteDynamicHeader",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_DYNAMIC_HEADER",
    name: "deleteDynamicHeader",
  },
  EDIT_COLUMN_NAME_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Goal/updateDynamicHeader",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_COLUMN_NAME",
    name: "editColumnName",
  },

  ADD_NEW_DYNAMIC_DROPDOWN_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/createHeaderDropdown",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_NEW_DYNAMIC_DROPDOWN_OPTION",
    name: "addNewDynamicDropdownOption",
  },
  GET_DYNAMIC_DROPDOWN_OPTIONS_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Goal/getAllHeaderDropdownByValueId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_DYNAMIC_DROPDOWN_OPTION",
    name: "getDynamicDropdownOptions",
  },
  UPDATE_DYNAMIC_DROPDOWN_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Goal/updateHeaderDropdown",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_DYNAMIC_DROPDOWN_OPTION",
    name: "updateDynamicDropdownOption",
  },
  DELETE_DYNAMIC_DROPDOWN_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteHeaderDropdownById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_DYNAMIC_DROPDOWN_OPTION",
    name: "deleteDynamicDropdownOption",
  },
  GET_ALL_THERAPIST_LIST_IN_GOAL_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Goal/getAllTherapist",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_THERAPIST_LIST_IN_GOAL_GROUP",
    name: "getAllTherapistListInGoalGroup",
  },

  ADD_NEW_DYNAMIC_HEADER_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/createDynamicHeader",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_NEW_DYNAMIC_HEADER_API",
    name: "addNewDynamicHeader",
  },
  ADD_NEW_GOAL_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/addGoalRow",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_NEW_GOAL",
    name: "addNewGoal",
  },

  DELETE_GOAL_ROW_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/removeGoalRow",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_GOAL_ROW",
    name: "deleteGoalRow",
  },
  ASSIGN_THERAPIST_IN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Goal/assignTherapist",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ASSIGN_THERAPIST_IN_GROUP",
    name: "assignTherapistInGroup",
  },
  UN_ASSIGN_THERAPIST_IN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteTherpistById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UN_ASSIGN_THERAPIST_IN_GROUP",
    name: "unAssignTherapistInGroup",
  },
  UN_ASSIGN_ALL_THERAPIST_IN_GROUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "Goal/deleteAllTherapistByGoalId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UN_ASSIGN_ALL_THERAPIST_IN_GROUP",
    name: "unAssignAllTherapistInGroup",
  },
  EDIT_HEADER_VALUES_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Goal/updateHeaderValues",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_HEADER_VALUES",
    name: "editHeaderValues",
  },
  // ************MY APIS CLOSED***********************
  INSURANCE_COMPANY_CREATE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "InsuranceCompany/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "INSURANCE_COMPANY_CREATE",
    name: "insuranceCompanyCreate",
  },
  INSURANCE_COMPANY_DROPDOWN_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "InsuranceCompany/insuranceCompanyDropdown",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "INSURANCE_COMPANY_DROPDOWN",
    name: "insuranceCompanyDropDown",
  },
  PLACE_OF_SERVICE_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=placeOfService",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "PLACE_OF_SERVICE_LOOKUP",
    name: "placeOfServiceLookup",
  },
  ADDRESS_TYPE_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=addressType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADDRESS_TYPE_LOOKUP",
    name: "addressTypeLookup",
  },
  RELATED_CAUSE_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=relatedCause",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "RELATED_CAUSE_LOOKUP",
    name: "relatedCauseLookup",
  },
  MARKETING_REFERRAL_CONTACT_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=marketingReferralContact",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "MARKETING_REFERRAL_CONTACT_LOOKUP",
    name: "marketingReferralContact",
  },
  PHYSICIAN_DROPDOWN_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Physician/physicianDropdown",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "PHYSICIAN_DROPDOWN",
    name: "physicianDropDown",
  },
  PATIENT_DROPDOWN_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Patient/getAllPatientDropdownByClinicId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "PATIENT_DROPDOWN",
    name: "patientDropDown",
  },
  UPDATE_PATIENT_STATUS_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/updateStatus",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_STATUS",
    name: "updatePatientStatus",
  },

  CREATE_PATIENT_CASE_DETAIL_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Patient/createCaseDetail",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_PATIENT_CASE_DETAIL_ID",
    name: "createPatientCaseDetailId",
  },

  UPDATE_PATIENT_IDENTIFICATION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientIdentification",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_IDENTIFICATION",
    name: "updatePatientIdentification",
  },
  CREATE_UPDATE_PATIENT_CONTACT_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientContact",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_UPDATE_PATIENT_CONTACT",
    name: "createUpdatePatientContact",
  },

  GET_PATIENT_GENERAL_BY_PATIENT_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Patient/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_PATIENT_GENERAL_BY_PATIENT_ID",
    name: "getPatientGeneralByPatientId",
  },
  UPDATE_PATIENT_CASE_DETAIL_NAME_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/updateCaseDetail",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_CASE_DETAIL_NAME",
    name: "createPatientCaseDetailId",
  },

  GET_PATIENT_CASES_BY_PATIENT_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Patient/getPatientCaseByPatientId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_PATIENT_CASES_BY_PATIENT_ID",
    name: "getPatientCasesByPatientId",
  },
  CREATE_UPDATE_PATIENT_ADDRESS_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientAddress",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_UPDATE_PATIENT_ADDRESS",
    name: "createUpdatePatientAddress",
  },
  UPDATE_PATIENT_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/updatePatient",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT",
    name: "updatePatient",
  },
  SPECIALITY_DROPDOWN_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Specialities/gtAllByClinicId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "SPECIALITY_DROPDOWN",
    name: "specialityDropDown",
  },
  AUTHORIZED_VISITED_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=authorizedVisited",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "AUTHORIZED_VISITED_LOOKUP",
    name: "authorizedVisitedLookup",
  },
  GET_PATIENT_INSURANCES_BY_PATIENT_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Patient/getPatientInsuranceByPatientId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_PATIENT_INSURANCES_BY_PATIENT_ID",
    name: "getPatientInsuranceByPatientId",
  },
  GET_PATIENT_INSURANCES_BY_PATIENT_ID_DROPDOWN_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Patient/getAllPatientInsuranceDropdownByPatientId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_PATIENT_INSURANCES_BY_PATIENT_ID_DROPDOWN",
    name: "getPatientInsuranceByPatientIdDropDown",
  },
  CREATE_PATIENT_CASE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Patient/createPatientCase",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_PATIENT_CASE",
    name: "createPatientCase",
  },
  UPDATE_PATIENT_CASE_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientCase",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_CASE",
    name: "updatePatientCase",
  },
  UPDATE_PATIENT_CASE_PRESCRIPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdateCasePrescription",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_CASE_PRESCRIPTION",
    name: "updatePatientPrescription",
  },
  UPDATE_PATIENT_CASE_AUTHORIZATION_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdateCaseAuthorization",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_CASE_AUTHORIZATION",
    name: "updatePatientAuthorization",
  },
  UPDATE_PATIENT_CASE_CERTIFICATES_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdateCaseCertificate",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_CASE_CERTIFICATES",
    name: "updatePatientCertificates",
  },
  INSURANCE_COMPANY_GET_ALL_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "InsuranceCompany/getAll",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "INSURANCE_COMPANY_GET_ALL",
    name: "insuranceCompanyGetAll",
  },
  EDIT_INSURANCE_COMPANY_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "InsuranceCompany/update",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_INSURANCE_COMPANY",
    name: "editInsuranceCompany",
  },

  // ######## GET ALL MODIFIERS API ###########
  INSURANCE_MODIFIERS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Modifiers/getAll",
      data: null,
    },
    totalRecords: null,
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALL_MODIFIERS",
    name: "getallmodifiers",
  },
  // ########
  // ######## ADD MODIFIERS API ###########
  ADD_INSURANCE_MODIFIERS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Modifiers/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_MODIFIERS",
    name: "addmodifiers",
  },
  // ######## GET ALL MODIFIERS API ###########

  // ######## GET SINGLE MODIFIERS API ###########
  GETSINGLE_INSURANCE_MODIFIERS_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Modifiers/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETINSURANCE_MODIFIERS",
    name: "getsinglemodifiers",
  },
  GET_MODIFIERS_BY_DETERMINATION_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Modifiers/getModifiersByDetermination",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_MODIFIERS_BY_DETERMINATION",
    name: "getModifiersByDetermination",
  },
  // ######## EDIT MODIFIERS API ###########
  EDIT_INSURANCE_MODIFIERS_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Modifiers/update",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_MODIFIERS",
    name: "editmodifiers",
  },
  // ######## ADD FEE SCHEDULE API ###########
  ADD_INSURANCE_FEESCHEDULE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "FeeSchedular/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_FEESCHEDULE",
    name: "addfeeschedule",
  },
  // ######## GET ALL FEE SCHEDULE API ###########
  GETALL_INSURANCE_FEESCHEDULE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "FeeSchedular/getAll",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "INSURANCE_MODIFIERS",
    name: "getallfeeschedule",
  },
  // ######## GET SINGLE FEE SCHEDULE API ###########
  GETSINGLE_INSURANCE_FEESCHEDULE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "FeeSchedular/getCptCodesByFeeSchedularId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETSINGLEINSURANCE_FEESCHEDULE",
    name: "getsinglefeeschedule",
  },
  // ######## EDIT FEE SCHEDULE API ###########
  EDIT_FEE_SCHEDULE_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "FeeSchedular/update",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_FEESCHEDULE",
    name: "editfeeschedule",
  },
  // ######## ADD CPT CODE API ###########
  ADD_INSURANCE_CPT_CODE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "FeeSchedular/cptCodesCreate",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_CPTCODE",
    name: "addcptcode",
  },
  // ######## GET CPT code by FEE SCHEDULE API ###########
  GET_INSURANCE_CPTCODE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "FeeSchedular/getCptCodesByFeeSchedularId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETCPTCODE_FEESCHEDULE",
    name: "getcptcode",
  },
  // ######## GET SINGLE CPT CODE API ###########
  GETSINGLE_CPT_CODE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "FeeSchedular/getCptCodeId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETSINGLE_CPT_CODE",
    name: "getsinglecptcode",
  },
  // ######## EDIT CPT CODE API ###########
  EDIT_CPT_CODE_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "FeeSchedular/updateCptCode",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_CPTCODE",
    name: "editcptcode",
  },
  // ######## ADD CLINIC API ###########
  ADD_CLINIC_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Clinics/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_CLINIC",
    name: "addclinic",
  },
  // ######## GET ALL CLINIC API ###########
  GETALL_CLINIC_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Clinics/getAllClinicList",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALL_CLINIC",
    name: "getallclinic",
  },
  GETALL_CLINIC_LIST_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Clinics/getClinicDropdownList",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALL_CLINIC_LIST",
    name: "getallclinicList",
  },
  GET_ALL_USER_CLINICS_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Clinics/getAllHeaderClinics",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_USER_CLINICS",
    name: "getAllUserClinics",
  },
  // ######## GET SINGLE CLINIC API ###########
  GETSINGLE_CLINIC_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Clinics/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETSINGLE_CLINIC",
    name: "getsingleclinic",
  },

  UPDATE_CLINIC_BY_USER_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/updateCurrentClinicByUserId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_CLINIC_BY_USER_ID_API",
    name: "updateClinicByUserId",
  },

  GET_CURRENT_CLINIC_BY_USER_ID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getCurrentClinicByUserId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_CURRENT_CLINIC_BY_USER_ID",
    name: "getCurrentClinicByUserId",
  },
  // ######## EDIT CLINIC API ###########
  EDIT_CLINIC_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Clinics/update",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_CLINIC",
    name: "editclinic",
  },
  // ######## ADD USER API ###########
  ADD_USER_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Account/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_USER",
    name: "adduser",
  },
  // ######## GET ALL USER API ###########
  GETALL_USER_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Account/getAllUsersList",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALL_USER",
    name: "getalluser",
  },
  // ######## GET SINGLE USER API ###########
  GETSINGLE_USER_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Account/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETSINGLE_USER",
    name: "getsingleuser",
  },
  // ######## EDIT USER API ###########
  EDIT_USER_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Account/update",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_USER",
    name: "edituser",
  },
  // ######## UPDATE USER STATUS API ###########
  UPDATE_USER_STATUS_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Account/updateStatus",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_USER_STATUS",
    name: "updateUserStatus",
  },
  // ######## GET CHECKBOX SETTING USER API ###########
  GET_CHECKBOX_SETTING_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Account/getAllClericalAssignTaskList",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_CHECKBOX_SETTING",
    name: "getcheckboxsettinguser",
  },
  // ####### LOGIN API #########
  LOGIN_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Login/login",
      data: null,
      headers: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "VERIFY_USERNAME",
    name: "verifyUser",
  },
  VERIFY_OTP_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Login/loginCpt",
      data: null,
      headers: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "VERIFY_OTP",
    name: "verifyOtp",
  },
  FORGOT_PASSWORD_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Login/forgotPassword",
      data: null,
      headers: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "FORGOT_PASSWORD",
    name: "forgotPassword",
  },
  RESET_PASSWORD_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Login/resetPassword",
      data: null,
      headers: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "RESET_PASSWORD",
    name: "resetPassword",
  },
  // ######## ADD INSURANCE TYPE API ###########
  ADD_INSURANCE_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "InsuranceType/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_INSURANCE_TYPE",
    name: "addInurenceType",
  },
  // ######## GET INSURANCE TYPE SETTING API ###########
  GET_INSURANCE_TYPE_SETTING_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "InsuranceType/getAllCaseReq",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_INSURANCE_TYPE",
    name: "getinsurancetypesetting",
  },
  // ######## GET ALL INSURANCE TYPE API ###########
  GETALL_INSURANCE_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "InsuranceType/getAll",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALL_INSURANCE_TYPE",
    name: "getallInsuranceType",
  },
  INSURANCE_TYPE_DROPDOWN_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "InsuranceType/insuranceTypeDropdown",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "INSURANCE_TYPE_DROPDOWN",
    name: "insuranceTypeDropDown",
  },
  // ######## GET SINGLE SINGLE INSURANCE TYPE API ###########
  GETSINGLE_INSURANCE_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "InsuranceType/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETSINGLE_INSURANCE_TYPE",
    name: "getsingleInsuranceType",
  },
  // ######## ADD INSURANCE TYPE CREATE MODIFIERS API ###########
  ADD_CREATE_MODIFIERS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "InsuranceType/createModifier",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_CREATE_MODIFIERS",
    name: "addCreateModifiers",
  },
  // ########## Delete INSURANCE TYPE CREATE MODIFIERS API #######
  DELETE_SINGLE_CREATE_MODIFIERS_OPTION_API: {
    data: {
      urlExtension: null,
      apiMethod: "delete",
      url: baseUrl + "InsuranceType/deleteModifierbyId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DELETE_SINGLE_CREATE_MODIFIERS_OPTION",
    name: "deleteSinglecreatemodifiersOption",
  },
  // ######## EDIT INSURANCE TYPE API ###########
  EDIT_INSURANCE_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "InsuranceType/update",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_INSURANCE_TYPE",
    name: "editinsuranceType",
  },

  EDIT_INSURANCE_TYPE_SETTINGS_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "InsuranceType/updateSettings",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_INSURANCE_TYPE_SETTINGS",
    name: "editInsuranceTypeSettings",
  },
  EDIT_INSURANCE_COMPANY_SETTINGS_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "InsuranceCompany/updateSettings",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "EDIT_INSURANCE_COMPANY_SETTINGS",
    name: "editInsuranceCompanySettings",
  },

  GET_SINGLE_INSURANCE_COMPANY_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "InsuranceCompany/getById",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_SINGLE_INSURANCE_COMPANY",
    name: "getsingleInsuranceCompany",
  },

  GETALLUSER_ROLESANDPERMISSION_BYUSER_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "RolesAndPermission/getAllUsersByUserType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALLUSER_ROLESANDPERMISSION_BYUSER_TYPE",
    name: "getAllUserRolesAndPermisssion",
  },
  GETALL_MODULES_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "RolesAndPermission/getAllModules",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALL_MODULES",
    name: "getAllModules",
  },
  ADD_ROLESANDPERMISSIONS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "RolesAndPermission/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "ADD_ROLESANDPERMISSIONS",
    name: "addRolesAndPermissions",
  },
  GETBY_USERID_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "RolesAndPermission/getByUserId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETBY_USER_ID",
    name: "getByUserId",
  },
  Update_RolesAndPermission_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "RolesAndPermission/update",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "Update_RolesAndPermission",
    name: "updateRolesAndPermission",
  },

  GET_ALL_THERAPIST_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Appointments/getAllTherapistByUserTypeIdAndClinicId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_THERAPIST",
    name: "getAllTherapist",
  },
  FREQUENCY_DROPDOWN_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=Frequency",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "FREQUENCY_DROPDOWN_LOOKUP",
    name: "frequencyDropdownLookup",
  },
  DURATION_DROPDOWN_LOOKUP_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=duration",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "DURATION_DROPDOWN_LOOKUP",
    name: "durationDropdownLookup",
  },
  GET_ALL_SCHEDULE_APPOINTMENTS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Appointments/GetAllScheduleAppointments",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_SCHEDUALEAPPOINTMENTS",
    name: "getAllScheduleAppointment",
  },
  CREATE_SCHEDULE_APPOINTMENTS_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Appointments/CreateScheduleAppointment",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_SCHEDUALEAPPOINTMENTS",
    name: "createScheduleAppointment",
  },
  UPDATE_SCHEDULE_APPOINTMENTS_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Appointments/updateScheduleAppointment",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_SCHEDUALE_APPOINTMENTS",
    name: "updateScheduleAppointment",
  },
  // ######## GET ALL PATIENTS API ###########
  GET_ALL_PATIENT_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Patient/getAll",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GETALL_PATIENTS",
    name: "getAllPatient",
  },

  // ######## GET ALL PATIENTS/CASES API ###########
  GET_ALL_PATIENT_CASE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Patient/getAllPatientCaseDropdownByPatientId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_PATIENTCASE",
    name: "getAllPatientCase",
  },
  LOOKUP_APPOINTMENT_TYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=AppointmentType",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_APPOINTMENTTYPE",
    name: "lookUpAppoitmentTypeType",
  },
  LOOKUP_APPOINTMENTSTATUS_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=AppointmentStatus",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_APPOINTMENTSTATUS",
    name: "lookUpAppointmentStatus",
  },
  LOOKUP_APPOINTMENT_DURATION_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=AppointmentDuration",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_APPOINTMENTDURATION",
    name: "lookUpAppointmentDuration",
  },
  // ######## CREATE PATIENT INSURANCE DETAIL API ###########
  CREATE_PATIENT_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Patient/createPatient",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_PATIENT",
    name: "createPatient",
  },
  UPDATE_PATIENT_INSURANCE_GENERAL_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientInsurance",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_INSURANCE_GENERAL",
    name: "updatePatientInsuranceGeneral",
  },
  UPDATE_PATIENT_INSURANCE_BENEFITS_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientInsuranceBenefits",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_INSURANCE_BENEFITS",
    name: "updatePatientInsuranceBenfits",
  },
  UPDATE_PATIENT_INSURANCE_INSURED_PARTY_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientInsuredParty",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_INSURANCE_INSURED_PARTY",
    name: "updatePatientInsuranceInsuredParty",
  },
  UPDATE_PATIENT_INSURANCE_GUARANTOR_PARTY_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Patient/createUpdatePatientGuarantorParty",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "UPDATE_PATIENT_INSURANCE_GUARANTOR_PARTY",
    name: "updatePatientInsuranceGuarantorParty",
  },

  CREATE_PATIENT_INSURANCE_DETAIL_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Patient/createInsuranceDetail",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_PATIENT_INSURANCE_DETAIL",
    name: "createPatientInsuranceDetail",
  },
  CREATE_PATIENT_INSURANCE_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Patient/createPatientInsurance",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_PATIENT_INSURANCE",
    name: "createPatientInsurance",
  },

  CREATE_FAX_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Fax/create",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "CREATE_FAX",
    name: "createFax",
  },

  LOOKUP_CASETYPE_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Lookup/getAll?type=casetype",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "LOOKUP_CASETYPE",
    name: "lookUpCaseType",
  },

  FAX_HISTORY_API: {
    data: {
      urlExtension: null,
      apiMethod: "post",
      url: baseUrl + "Fax/getAll",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "FAX_HISTORY",
    name: "faxhistory",
  },

  REFAX_API: {
    data: {
      urlExtension: null,
      apiMethod: "put",
      url: baseUrl + "Fax/reFaxByFaxId",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "REFAX_API",
    name: "reFax",
  },
  GET_ALL_APPOINTMENTS_BY_NAME_API: {
    data: {
      urlExtension: null,
      apiMethod: "get",
      url: baseUrl + "Appointments/getAllTherapistByClinicIdAndTherapistName",
      data: null,
    },
    functionOnSuccess: null,
    functionOnFailureResponse: null,
    functionOnFailureError: null,
    type: "GET_ALL_APPOINTMENTS_BY_NAME",
    name: "getAllAppointmentsByName",
  },
};
