function request(actionType, allType) {
  return {
    type: actionType,
    payload: allType,
  };
}
function success(actionType, response) {
  return {
    type: actionType,
    payload: response,
  };
}
function failure(actionType, error) {
  return {
    type: actionType,
    payload: error,
  };
}
const PATIENTS = {
  GET_ALL_PATIENT_LOADING: " GET_ALL_PATIENT_LOADING",
  GET_ALL_PATIENT_SUCCESS: " GET_ALL_PATIENT_SUCCESS",
  GET_ALL_PATIENT_FAILURE: " GET_ALL_PATIENT_FAILURE",
  GET_ALL_PATIENT_DROPDOWN_LOADING: " GET_ALL_PATIENT_DROPDOWN_LOADING",
  GET_ALL_PATIENT_DROPDOWN_SUCCESS: " GET_ALL_PATIENT_DROPDOWN_SUCCESS",
  GET_ALL_PATIENT_DROPDOWN_FAILURE: " GET_ALL_PATIENT_DROPDOWN_FAILURE",
  GET_PATIENT_CASE_DROPDOWN_LOADING: " GET_PATIENT_CASE_DROPDOWN_LOADING",
  GET_PATIENT_CASE_DROPDOWN_SUCCESS: " GET_PATIENT_CASE_DROPDOWN_SUCCESS",
  GET_PATIENT_CASE_DROPDOWN_FAILURE: " GET_PATIENT_CASE_DROPDOWN_FAILURE",
  GET_CASE_BY_CASE_ID_LOADING: " GET_CASE_BY_CASE_ID_LOADING",
  GET_CASE_BY_CASE_ID_SUCCESS: " GET_CASE_BY_CASE_ID_SUCCESS",
  GET_CASE_BY_CASE_ID_FAILURE: " GET_CASE_BY_CASE_ID_FAILURE",
  CREATE_PATIENT_CASE_FILE_LOADING: " CREATE_PATIENT_CASE_FILE_LOADING",
  CREATE_PATIENT_CASE_FILE_SUCCESS: " CREATE_PATIENT_CASE_FILE_SUCCESS",
  CREATE_PATIENT_CASE_FILE_FAILURE: " CREATE_PATIENT_CASE_FILE_FAILURE",
  GET_REFERRAL_FILES_BY_ID_LOADING: "GET_REFERRAL_FILES_BY_ID_LOADING",
  GET_REFERRAL_FILES_BY_ID_SUCCESS: "GET_REFERRAL_FILES_BY_ID_SUCCESS",
  GET_REFERRAL_FILES_BY_ID_FAILURE: "GET_REFERRAL_FILES_BY_ID_FAILURE",
  GET_CASE_FILES_BY_CASE_ID_LOADING: "GET_CASE_FILES_BY_CASE_ID_LOADING",
  GET_CASE_FILES_BY_CASE_ID_SUCCESS: "GET_CASE_FILES_BY_CASE_ID_SUCCESS",
  GET_CASE_FILES_BY_CASE_ID_FAILURE: "GET_CASE_FILES_BY_CASE_ID_FAILURE",
};
const REFERRAL_MANAGEMENT = {
  GET_SPECIALITY_PATIENTS_COUNT_LOADING:
    " GET_SPECIALITY_PATIENTS_COUNT_LOADING",
  GET_SPECIALITY_PATIENTS_COUNT_SUCCESS:
    " GET_SPECIALITY_PATIENTS_COUNT_SUCCESS",
  GET_SPECIALITY_PATIENTS_COUNT_FAILURE:
    " GET_SPECIALITY_PATIENTS_COUNT_FAILURE",

  GET_REFERRAL_PATIENT_BY_SPECIALITY_ID_LOADING:
    " GET_REFERRAL_PATIENT_BY_SPECIALITY_ID_LOADING",
  GET_REFERRAL_PATIENT_BY_SPECIALITY_ID_SUCCESS:
    " GET_REFERRAL_PATIENT_BY_SPECIALITY_ID_SUCCESS",
  GET_REFERRAL_PATIENT_BY_SPECIALITY_ID_FAILURE:
    " GET_REFERRAL_PATIENT_BY_SPECIALITY_ID_FAILURE",

  GET_ALL_DATA_BY_REFERRAL_PATIENT_ID_LOADING:
    " GET_ALL_DATA_BY_REFERRAL_PATIENT_ID_LOADING",
  GET_ALL_DATA_BY_REFERRAL_PATIENT_ID_SUCCESS:
    " GET_ALL_DATA_BY_REFERRAL_PATIENT_ID_SUCCESS",
  GET_ALL_DATA_BY_REFERRAL_PATIENT_ID_FAILURE:
    " GET_ALL_DATA_BY_REFERRAL_PATIENT_ID_FAILURE",

  GET_CLERICAL_DROPDOWN_BY_CLINIC_ID_LOADING:
    "GET_CLERICAL_DROPDOWN_BY_CLINIC_ID_LOADING",
  GET_CLERICAL_DROPDOWN_BY_CLINIC_ID_SUCCESS:
    "GET_CLERICAL_DROPDOWN_BY_CLINIC_ID_SUCCESS",
  GET_CLERICAL_DROPDOWN_BY_CLINIC_ID_FAILURE:
    "GET_CLERICAL_DROPDOWN_BY_CLINIC_ID_FAILURE",

  CREATE_CALL_LOADING: "CREATE_CALL_LOADING",
  CREATE_CALL_SUCCESS: "CREATE_CALL_SUCCESS",
  CREATE_CALL_FAILURE: "CREATE_CALL_FAILURE",

  UPDATE_CALL_LOG_LOADING: "UPDATE_CALL_LOG_LOADING",
  UPDATE_CALL_LOG_SUCCESS: "UPDATE_CALL_LOG_SUCCESS",
  UPDATE_CALL_LOG_FAILURE: "UPDATE_CALL_LOG_FAILURE",

  UPDATE_REFERRAL_DETAILS_LOADING: "UPDATE_REFERRAL_DETAILS_LOADING",
  UPDATE_REFERRAL_DETAILS_SUCCESS: "UPDATE_REFERRAL_DETAILS_SUCCESS",
  UPDATE_REFERRAL_DETAILS_FAILURE: "UPDATE_REFERRAL_DETAILS_FAILURE",

  CREATE_MESSAGE_LOADING: "CREATE_MESSAGE_LOADING",
  CREATE_MESSAGE_SUCCESS: "CREATE_MESSAGE_SUCCESS",
  CREATE_MESSAGE_FAILURE: "CREATE_MESSAGE_FAILURE",

  CREATE_CALL_BACK_LOADING: "CREATE_CALL_BACK_LOADING",
  CREATE_CALL_BACK_SUCCESS: "CREATE_CALL_BACK_SUCCESS",
  CREATE_CALL_BACK_FAILURE: "CREATE_CALL_BACK_FAILURE",
};
const FAX = {
  CREATE_FAX_LOADING: " CREATE_FAX_LOADING",
  CREATE_FAX_SUCCESS: " CREATE_FAX_SUCCESS",
  CREATE_FAX_FAILURE: " CREATE_FAX_FAILURE",
  GET_FAX_BY_ID_LOADING: " GET_FAX_BY_ID_LOADING",
  GET_FAX_BY_ID_SUCCESS: " GET_FAX_BY_ID_SUCCESS",
  GET_FAX_BY_ID_FAILURE: " GET_FAX_BY_ID_FAILURE",
  RESEND_FAX_LOADING: " RESEND_FAX_LOADING",
  RESEND_FAX_SUCCESS: " RESEND_FAX_SUCCESS",
  RESEND_FAX_FAILURE: " RESEND_FAX_FAILURE",
};

const CLINIC_SETTINGS = {
  ADD_BUSINESS_OPERATING_HOURS_LOADING: " ADD_BUSINESS_OPERATING_HOURS_LOADING",
  ADD_BUSINESS_OPERATING_HOURS_SUCCESS: " ADD_BUSINESS_OPERATING_HOURS_SUCCESS",
  ADD_BUSINESS_OPERATING_HOURS_FAILURE: " ADD_BUSINESS_OPERATING_HOURS_FAILURE",

  GET_ALL_BUSINESS_OPERATING_HOURS_LOADING:
    "GET_ALL_BUSINESS_OPERATING_HOURS_LOADING",
  GET_ALL_BUSINESS_OPERATING_HOURS_SUCCESS:
    "GET_ALL_BUSINESS_OPERATING_HOURS_SUCCESS",
  GET_ALL_BUSINESS_OPERATING_HOURS_FAILURE:
    "GET_ALL_BUSINESS_OPERATING_HOURS_FAILURE",

  EDIT_BUSINESS_OPERATING_HOURS_LOADING:
    "EDIT_BUSINESS_OPERATING_HOURS_LOADING",
  EDIT_BUSINESS_OPERATING_HOURS_SUCCESS:
    "EDIT_BUSINESS_OPERATING_HOURS_SUCCESS",
  EDIT_BUSINESS_OPERATING_HOURS_FAILURE:
    "EDIT_BUSINESS_OPERATING_HOURS_FAILURE",
};
const INBOX = {
  CREATE_UPDATE_PATIENT_INBOX_LOADING: " CREATE_UPDATE_PATIENT_INBOX_LOADING",
  CREATE_UPDATE_PATIENT_INBOX_SUCCESS: " CREATE_UPDATE_PATIENT_INBOX_SUCCESS",
  CREATE_UPDATE_PATIENT_INBOX_FAILURE: " CREATE_UPDATE_PATIENT_INBOX_FAILURE",
  CREATE_UPDATE_REFERRAL_INBOX_LOADING: " CREATE_UPDATE_REFERRAL_INBOX_LOADING",
  CREATE_UPDATE_REFERRAL_INBOX_SUCCESS: " CREATE_UPDATE_REFERRAL_INBOX_SUCCESS",
  CREATE_UPDATE_REFERRAL_INBOX_FAILURE: " CREATE_UPDATE_REFERRAL_INBOX_FAILURE",
};
const FORM_DR = {
  GET_FORM_DR_TOKEN_LOADING: " GET_FORM_DR_TOKEN_LOADING",
  GET_FORM_DR_TOKEN_SUCCESS: " GET_FORM_DR_TOKEN_SUCCESS",
  GET_FORM_DR_TOKEN_FAILURE: " GET_FORM_DR_TOKEN_FAILURE",
  GET_PRACTICE_LOADING: " GET_PRACTICE_LOADING",
  GET_PRACTICE_SUCCESS: " GET_PRACTICE_SUCCESS",
  GET_PRACTICE_FAILURE: " GET_PRACTICE_FAILURE",
  GET_FORMS_LOADING: " GET_FORMS_LOADING",
  GET_FORMS_SUCCESS: " GET_FORMS_SUCCESS",
  GET_FORMS_FAILURE: " GET_FORMS_FAILURE",

  GET_SUBMISSION_FILE_LOADING: " GET_SUBMISSION_FILE_LOADING",
  GET_SUBMISSION_FILE_SUCCESS: " GET_SUBMISSION_FILE_SUCCESS",
  GET_SUBMISSION_FILE_FAILURE: " GET_SUBMISSION_FILE_FAILURE",

  GET_SUBMISSIONS_LOADING: " GET_SUBMISSIONS_LOADING",
  GET_SUBMISSIONS_SUCCESS: " GET_SUBMISSIONS_SUCCESS",
  GET_SUBMISSIONS_FAILURE: " GET_SUBMISSIONS_FAILURE",
};

const REFFERAL = {
  GET_ALL_REFFERALS_LOADING: "GET_ALL_REFFERALS_LOADING",
  GET_ALL_REFFERALS_SUCCESS: "GET_ALL_REFFERALS_SUCCESS",
  GET_ALL_REFFERALS_FAILURE: "GET_ALL_REFFERALS_FAILURE",
  CREATE_PATIENT_REFFERAL_LOADING: "CREATE_PATIENT_REFFERAL_LOADING",
  CREATE_PATIENT_REFFERAL_SUCCESS: "CREATE_PATIENT_REFFERAL_SUCCESS",
  CREATE_PATIENT_REFFERAL_FAILURE: "CREATE_PATIENT_REFFERAL_FAILURE",
  UPDATE_REFFERAL_LOADING: "UPDATE_REFFERAL_LOADING",
  UPDATE_REFFERAL_SUCCESS: "UPDATE_REFFERAL_SUCCESS",
  UPDATE_REFFERAL_FAILURE: "UPDATE_REFFERAL_FAILURE",
  GET_REFFERAL_BY_ID_LOADING: "GET_REFFERAL_BY_ID_LOADING",
  GET_REFFERAL_BY_ID_SUCCESS: "GET_REFFERAL_BY_ID_SUCCESS",
  GET_REFFERAL_BY_ID_FAILURE: "GET_REFFERAL_BY_ID_FAILURE",
  GET_REFERRAL_DROPDOWN_LOADING: "GET_REFERRAL_DROPDOWN_LOADING",
  GET_REFERRAL_DROPDOWN_SUCCESS: "GET_REFERRAL_DROPDOWN_SUCCESS",
  GET_REFERRAL_DROPDOWN_FAILURE: "GET_REFERRAL_DROPDOWN_FAILURE",
};
const BUCKET = {
  UPLOAD_FILE_REQUEST: "UPLOAD_FILE_REQUEST",
  UPLOAD_FILE_SUCCESS: "UPLOAD_FILE_SUCCESS",
  UPLOAD_FILE_FAILURE: "UPLOAD_FILE_FAILURE",
  UPLOAD_FILE_ASYNC_REQUEST: "UPLOAD_FILE_ASYNC_REQUEST",
  UPLOAD_FILE_ASYNC_SUCCESS: "UPLOAD_FILE_ASYNC_SUCCESS",
  UPLOAD_FILE_ASYNC_FAILURE: "UPLOAD_FILE_ASYNC_FAILURE",
};
const SPECIALITIES_TYPE = {
  GET_ALL_CLINIC_SPECIALITIES_LOADING: "GET_ALL_CLINIC_SPECIALITIES_LOADING",
  GET_ALL_CLINIC_SPECIALITIES_SUCCESS: "GET_ALL_CLINIC_SPECIALITIES_SUCCESS",
  GET_ALL_CLINIC_SPECIALITIES_FAILURE: "GET_ALL_CLINIC_SPECIALITIES_FAILURE",
  ADD_SPECIALITY_LOADING: "ADD_SPECIALITY_LOADING",
  ADD_SPECIALITY_SUCCESS: "ADD_SPECIALITY_SUCCESS",
  ADD_SPECIALITY_FAILURE: "ADD_SPECIALITY_FAILURE",
  CHANGE_IN_CODE: "CHANGE_IN_CODE",
  CHANGE_IN_FORM: "CHANGE_IN_FORM",
  GET_BY_ID_LOADING: "GET_BY_ID_LOADING",
  GET_BY_ID_SUCCESS: "GET_BY_ID_SUCCESS",
  GET_BY_ID_FAILURE: "GET_BY_ID_FAILURE",
};
const TEMPLATES = {
  RESET_TEMPLATE: "RESET_TEMPLATE",
  GET_ALL_TEMPLATES_LOADING: "GET_ALL_TEMPLATES_LOADING",
  GET_ALL_TEMPLATES_SUCCESS: "GET_ALL_TEMPLATES_SUCCESS",
  GET_ALL_TEMPLATES_FAILURE: "GET_ALL_TEMPLATES_FAILURE",
  CREATE_TEMPLATE_LOADING: "CREATE_TEMPLATE_LOADING",
  CREATE_TEMPLATE_SUCCESS: "CREATE_TEMPLATE_SUCCESS",
  CREATE_TEMPLATE_FAILURE: "CREATE_TEMPLATE_FAILURE",
  UPDATE_TEMPLATE_LOADING: "UPDATE_TEMPLATE_LOADING",
  UPDATE_TEMPLATE_SUCCESS: "UPDATE_TEMPLATE_SUCCESS",
  UPDATE_TEMPLATE_FAILURE: "UPDATE_TEMPLATE_FAILURE",
  CREATE_TEMPLATE_FORM_LOADING: "CREATE_TEMPLATE_FORM_LOADING",
  CREATE_TEMPLATE_FORM_SUCCESS: "CREATE_TEMPLATE_FORM_SUCCESS",
  CREATE_TEMPLATE_FORM_FAILURE: "CREATE_TEMPLATE_FORM_FAILURE",
  GET_TEMPLATE_FORM_LOADING: "GET_TEMPLATE_FORM_LOADING",
  GET_TEMPLATE_FORM_SUCCESS: "GET_TEMPLATE_FORM_SUCCESS",
  GET_TEMPLATE_FORM_FAILURE: "GET_TEMPLATE_FORM_FAILURE",
  UPDATE_TEMPLATE_FORM_LOADING: "UPDATE_TEMPLATE_FORM_LOADING",
  UPDATE_TEMPLATE_FORM_SUCCESS: "UPDATE_TEMPLATE_FORM_SUCCESS",
  UPDATE_TEMPLATE_FORM_FAILURE: "UPDATE_TEMPLATE_FORM_FAILURE",
  ASSIGN_TEMPLATE_LOADING: "ASSIGN_TEMPLATE_LOADING",
  ASSIGN_TEMPLATE_SUCCESS: "ASSIGN_TEMPLATE_SUCCESS",
  ASSIGN_TEMPLATE_FAILURE: "ASSIGN_TEMPLATE_FAILURE",
  ASSIGN_AND_COPY_TEMPLATE_LOADING: "ASSIGN_AND_COPY_TEMPLATE_LOADING",
  ASSIGN_AND_COPY_TEMPLATE_SUCCESS: "ASSIGN_AND_COPY_TEMPLATE_SUCCESS",
  ASSIGN_AND_COPY_TEMPLATE_FAILURE: "ASSIGN_AND_COPY_TEMPLATE_FAILURE",
  THERAPIST_APPOINTMENT_NOTE_TEMPLATES_LOADING:
    "THERAPIST_APPOINTMENT_NOTE_TEMPLATES_LOADING",
  THERAPIST_APPOINTMENT_NOTE_TEMPLATES_SUCCESS:
    "THERAPIST_APPOINTMENT_NOTE_TEMPLATES_SUCCESS",
  THERAPIST_APPOINTMENT_NOTE_TEMPLATES_FAILURE:
    "THERAPIST_APPOINTMENT_NOTE_TEMPLATES_FAILURE",
  ADD_TEMPLATE_FOR_APPOINTMENT_NOTES_LOADING:
    "ADD_TEMPLATE_FOR_APPOINTMENT_NOTES_LOADING",
  ADD_TEMPLATE_FOR_APPOINTMENT_NOTES_SUCCESS:
    "ADD_TEMPLATE_FOR_APPOINTMENT_NOTES_SUCCESS",
  ADD_TEMPLATE_FOR_APPOINTMENT_NOTES_FAILURE:
    "ADD_TEMPLATE_FOR_APPOINTMENT_NOTES_FAILURE",
  UPDATE_TEMPLATE_FOR_APPOINTMENT_NOTES_LOADING:
    "UPDATE_TEMPLATE_FOR_APPOINTMENT_NOTES_LOADING",
  UPDATE_TEMPLATE_FOR_APPOINTMENT_NOTES_SUCCESS:
    "UPDATE_TEMPLATE_FOR_APPOINTMENT_NOTES_SUCCESS",
  UPDATE_TEMPLATE_FOR_APPOINTMENT_NOTES_FAILURE:
    "UPDATE_TEMPLATE_FOR_APPOINTMENT_NOTES_FAILURE",
};
const IMAGES_TEMPLATES = {
  ADD_REMOVE_IMAGE: "ADD_REMOVE_IMAGE",
  UPDATE_IMAGE: "UPDATE_IMAGE",
  ADD_UPDATE_IMAGE: "ADD_UPDATE_IMAGE",
};

const SR_FAX = {
  GET_SR_FAX_INBOX_LOADING: "GET_SR_FAX_INBOX_LOADING",
  GET_SR_FAX_INBOX_SUCCESS: "GET_SR_FAX_INBOX_SUCCESS",
  GET_SR_FAX_INBOX_FAILURE: "GET_SR_FAX_INBOX_FAILURE",
  RETRIEVE_FAX_LOADING: "RETRIEVE_FAX_LOADING",
  RETRIEVE_FAX_SUCCESS: "RETRIEVE_FAX_SUCCESS",
  RETRIEVE_FAX_FAILURE: "RETRIEVE_FAX_FAILURE",
  QUEUE_FAX_LOADING: "QUEUE_FAX_LOADING",
  QUEUE_FAX_SUCCESS: "QUEUE_FAX_SUCCESS",
  QUEUE_FAX_FAILURE: "QUEUE_FAX_FAILURE",
};
const REFFERAL_TEMPLATE = {
  CHANGE_IN_REFFERAL_CALL_TIME: "CHANGE_IN_REFFERAL_CALL_TIME",
  CREATE_UPDATE_REFFERAL_CALL_TIME_REQUEST:
    "CREATE_UPDATE_REFFERAL_CALL_TIME_REQUEST",
  CREATE_UPDATE_REFFERAL_CALL_TIME_SUCCESS:
    "CREATE_UPDATE_REFFERAL_CALL_TIME_SUCCESS",
  CREATE_UPDATE_REFFERAL_CALL_TIME_FAILURE:
    "CREATE_UPDATE_REFFERAL_CALL_TIME_FAILURE",

  GET_REFFERAL_CALL_TIME_REQUEST: "GET_REFFERAL_CALL_TIME_REQUEST",
  GET_REFFERAL_CALL_TIME_SUCCESS: "GET_REFFERAL_CALL_TIME_SUCCESS",
  GET_REFFERAL_CALL_TIME_FAILURE: "GET_REFFERAL_CALL_TIME_FAILURE",
};
const TASK = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
};

const APPOINTMENT = {
  GET_APPOINTMENT_BY_ID_REQUEST: "GET_APPOINTMENT_BY_ID_REQUEST",
  GET_APPOINTMENT_BY_ID_SUCCESS: "GET_APPOINTMENT_BY_ID_SUCCESS",
  GET_APPOINTMENT_BY_ID_FAILURE: "GET_APPOINTMENT_BY_ID_FAILURE",

  GET_ALL_APPOINTMENT_BY_PATIENT_ID_REQUEST:
    "GET_ALL_APPOINTMENT_BY_PATIENT_ID_REQUEST",
  GET_ALL_APPOINTMENT_BY_PATIENT_ID_SUCCESS:
    "GET_ALL_APPOINTMENT_BY_PATIENT_ID_SUCCESS",
  GET_ALL_APPOINTMENT_BY_PATIENT_ID_FAILURE:
    "GET_ALL_APPOINTMENT_BY_PATIENT_ID_FAILURE",

  UPDATE_APPOINTMENT_STATUS_REQUEST: "UPDATE_APPOINTMENT_STATUS_REQUEST",
  UPDATE_APPOINTMENT_STATUS_SUCCESS: "UPDATE_APPOINTMENT_STATUS_SUCCESS",
  UPDATE_APPOINTMENT_STATUS_FAILURE: "UPDATE_APPOINTMENT_STATUS_FAILURE",

  CREATE_REASON_STATUS_REQUEST: "CREATE_REASON_STATUS_REQUEST",
  CREATE_REASON_STATUS_SUCCESS: "CREATE_REASON_STATUS_SUCCESS",
  CREATE_REASON_STATUS_FAILURE: "CREATE_REASON_STATUS_FAILURE",

  GET_ALL_SCHEDULE_PAYMENT_REQUEST: "GET_ALL_SCHEDULE_PAYMENT_REQUEST",
  GET_ALL_SCHEDULE_PAYMENT_SUCCESS: "GET_ALL_SCHEDULE_PAYMENT_SUCCESS",
  GET_ALL_SCHEDULE_PAYMENT_FAILURE: "GET_ALL_SCHEDULE_PAYMENT_FAILURE",

  CREATE_UPDATE_SCHEDULE_PAYMENT_REQUEST:
    "CREATE_UPDATE_SCHEDULE_PAYMENT_REQUEST",
  CREATE_SCHEDULE_PAYMENT_SUCCESS: "CREATE_SCHEDULE_PAYMENT_SUCCESS",
  UPDATE_SCHEDULE_PAYMENT_SUCCESS: "UPDATE_SCHEDULE_PAYMENT_SUCCESS",
  CREATE_UPDATE_SCHEDULE_PAYMENT_FAILURE:
    "CREATE_UPDATE_SCHEDULE_PAYMENT_FAILURE",

  SAVE_CALL_RECORD_DETAILS_REQUEST: "SAVE_CALL_RECORD_DETAILS_REQUEST",
  SAVE_CALL_RECORD_DETAILS_SUCCESS: "SAVE_CALL_RECORD_DETAILS_SUCCESS",
  SAVE_CALL_RECORD_DETAILS_FAILURE: "SAVE_CALL_RECORD_DETAILS_FAILURE",

  GET_CANCELATION_PERCENTAGE_REQUEST: "GET_CANCELATION_PERCENTAGE_REQUEST",
  GET_CANCELATION_PERCENTAGE_SUCCESS: "GET_CANCELATION_PERCENTAGE_SUCCESS",
  GET_CANCELATION_PERCENTAGE_FAILURE: "GET_CANCELATION_PERCENTAGE_FAILURE",
  CREATE_UPDATE_PAYMENT_NOTES_REQUEST: "CREATE_UPDATE_PAYMENT_NOTES_REQUEST",
  CREATE_UPDATE_PAYMENT_NOTES_SUCCESS: "CREATE_UPDATE_PAYMENT_NOTES_SUCCESS",
  CREATE_UPDATE_PAYMENT_NOTES_FAILURE: "CREATE_UPDATE_PAYMENT_NOTES_FAILURE",
};

const APPOINTMENT_DISCRETION = {
  GET_ALL_APPOINTMENT_BY_THERAPIST_AND_DATE_REQUEST:
    "GET_ALL_APPOINTMENT_BY_THERAPIST_AND_DATE_REQUEST",
  GET_ALL_APPOINTMENT_BY_THERAPIST_AND_DATE_SUCCESS:
    "GET_ALL_APPOINTMENT_BY_THERAPIST_AND_DATE_SUCCESS",
  GET_ALL_APPOINTMENT_BY_THERAPIST_AND_DATE_FAILURE:
    "GET_ALL_APPOINTMENT_BY_THERAPIST_AND_DATE_FAILURE",

  UPDATE_PATIENT_APPOINTMENT_REQUEST: "UPDATE_PATIENT_APPOINTMENT_REQUEST",
  UPDATE_PATIENT_APPOINTMENT_SUCCESS: "UPDATE_PATIENT_APPOINTMENT_SUCCESS",
  UPDATE_PATIENT_APPOINTMENT_FAILURE: "UPDATE_PATIENT_APPOINTMENT_FAILURE",

  PATIENT_APPOINTMENT_DETIAL_REQUEST: "PATIENT_APPOINTMENT_DETIAL_REQUEST",
  PATIENT_APPOINTMENT_DETIAL_SUCCESS: "PATIENT_APPOINTMENT_DETIAL_SUCCESS",
  PATIENT_APPOINTMENT_DETIAL_FAILURE: "PATIENT_APPOINTMENT_DETIAL_FAILURE",
  GET_ALL_APPOINTMENT_CX_NO_SHOW_REQUEST:
    "GET_ALL_APPOINTMENT_CX_NO_SHOW_REQUEST",
  GET_ALL_APPOINTMENT_CX_NO_SHOW_SUCCESS:
    "GET_ALL_APPOINTMENT_CX_NO_SHOW_SUCCESS",
  GET_ALL_APPOINTMENT_CX_NO_SHOW_FAILURE:
    "GET_ALL_APPOINTMENT_CX_NO_SHOW_FAILURE",
};

const APPOINTMENT_NOTES = {
  UPDATE_APPOINTMENT_NOTES_IMAGES_REQUEST:
    "UPDATE_APPOINTMENT_NOTES_IMAGES_REQUEST",
  UPDATE_APPOINTMENT_NOTES_IMAGES_SUCCESS:
    "UPDATE_APPOINTMENT_NOTES_IMAGES_SUCCESS",
  UPDATE_APPOINTMENT_NOTES_IMAGES_FAILURE:
    "UPDATE_APPOINTMENT_NOTES_IMAGES_FAILURE",
  UPDATE_APPOINTMENT_NOTES_FORMS_REQUEST:
    "UPDATE_APPOINTMENT_NOTES_FORMS_REQUEST",
  UPDATE_APPOINTMENT_NOTES_FORMS_SUCCESS:
    "UPDATE_APPOINTMENT_NOTES_FORMS_SUCCESS",
  UPDATE_APPOINTMENT_NOTES_FORMS_FAILURE:
    "UPDATE_APPOINTMENT_NOTES_FORMS_FAILURE",
  GET_GOAL_TEMPLATES_REQUEST: "GET_GOAL_TEMPLATES_REQUEST",
  GET_GOAL_TEMPLATES_SUCCESS: "GET_GOAL_TEMPLATES_SUCCESS",
  GET_GOAL_TEMPLATES_FAILURE: "GET_GOAL_TEMPLATES_FAILURE",
  ADD_UPDATE_GOAL_NOTES_REQUEST: "ADD_UPDATE_GOAL_NOTES_REQUEST",
  ADD_UPDATE_GOAL_NOTES_SUCCESS: "ADD_UPDATE_GOAL_NOTES_SUCCESS",
  ADD_UPDATE_GOAL_NOTES_FAILURE: "ADD_UPDATE_GOAL_NOTES_FAILURE",
  GET_GOAL_NOTES_REQUEST: "GET_GOAL_NOTES_REQUEST",
  GET_GOAL_NOTES_SUCCESS: "GET_GOAL_NOTES_SUCCESS",
  GET_GOAL_NOTES_FAILURE: "GET_GOAL_NOTES_FAILURE",
  UPDATE_GOAL_VALUE_REQUEST: "UPDATE_GOAL_VALUE_REQUEST",
  UPDATE_GOAL_VALUE_SUCCESS: "UPDATE_GOAL_VALUE_SUCCESS",
  UPDATE_GOAL_VALUE_FAILURE: "UPDATE_GOAL_VALUE_FAILURE",
  REMOVE_GOAL_ROW_REQUEST: "REMOVE_GOAL_ROW_REQUEST",
  REMOVE_GOAL_ROW_SUCCESS: "REMOVE_GOAL_ROW_SUCCESS",
  REMOVE_GOAL_ROW_FAILURE: "REMOVE_GOAL_ROW_FAILURE",
};
const STICKY_NOTES = {
  CREATE_UPDATE_STICKY_NOTES_REQUEST: "CREATE_UPDATE_STICKY_NOTES_REQUEST",
  CREATE_UPDATE_STICKY_NOTES_SUCCESS: "CREATE_UPDATE_STICKY_NOTES_SUCCESS",
  CREATE_UPDATE_STICKY_NOTES_FAILURE: "CREATE_UPDATE_STICKY_NOTES_FAILURE",
};

const RING_RX = {
  CREATE_TOKEN_FROM_CREDENTIALS_LOADING:
    "CREATE_TOKEN_FROM_CREDENTIALS_LOADING",
  CREATE_TOKEN_FROM_CREDENTIALS_SUCCESS:
    "CREATE_TOKEN_FROM_CREDENTIALS_SUCCESS",
  CREATE_TOKEN_FROM_CREDENTIALS_FAILURE:
    "CREATE_TOKEN_FROM_CREDENTIALS_FAILURE",

  SEND_MESSAGE_LOADING: "SEND_MESSAGE_LOADING",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAILURE: "SEND_MESSAGE_FAILURE",

  TERMINATE_CALL_LOADING: "TERMINATE_CALL_LOADING",
  TERMINATE_CALL_SUCCESS: "TERMINATE_CALL_SUCCESS",
  TERMINATE_CALL_FAILURE: "TERMINATE_CALL_FAILURE",

  MAKE_CALL_LOADING: "MAKE_CALL_LOADING",
  MAKE_CALL_SUCCESS: "MAKE_CALL_SUCCESS",
  MAKE_CALL_FAILURE: "MAKE_CALL_FAILURE",
};
const SCHEDULE = {
  GET_DEFAULT_APPOINTMENT_DURATION_REQUEST:
    "GET_DEFAULT_APPOINTMENT_DURATION_REQUEST",
  GET_DEFAULT_APPOINTMENT_DURATION_SUCCESS:
    "GET_DEFAULT_APPOINTMENT_DURATION_SUCCESS",
  GET_DEFAULT_APPOINTMENT_DURATION_FAILURE:
    "GET_DEFAULT_APPOINTMENT_DURATION_FAILURE",
};

export {
  request,
  success,
  failure,
  TEMPLATES,
  SPECIALITIES_TYPE,
  PATIENTS,
  REFFERAL,
  BUCKET,
  INBOX,
  IMAGES_TEMPLATES,
  FORM_DR,
  SR_FAX,
  REFFERAL_TEMPLATE,
  FAX,
  RING_RX,
  REFERRAL_MANAGEMENT,
  SCHEDULE,
  APPOINTMENT,
  APPOINTMENT_DISCRETION,
  STICKY_NOTES,
  APPOINTMENT_NOTES,
  CLINIC_SETTINGS,
  TASK,
};
